# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the kernel DVB frontend device drivers.
#

dvb-usb-tbs5530-objs := tbs5530.o
obj-$(CONFIG_DVB_USB_TBS5530) += dvb-usb-tbs5530.o

obj-$(CONFIG_DVB_M88RS6060) += m88rs6060.o

obj-$(CONFIG_DVB_CXD2878) += cxd2878.o
